### ISSUE TITLE
Why does this package import a custom Action.php?

### ISSUE THREAD

**Issue by LorenzoSapora** [anaseqal/nova-import#11]
Running a diff on the two files, it seems to just be an older version of the Action.php already inside nova. I'll make a PR to remove it.

**Comment by anaseqal** [comment]
Hi,

If i remember correctly, i made a custom action because the core action throws error when you apply action on zero resource.. and since this package import resources and not doing real action on current resources i had to clone the action files and comment the count check..

i expect this issue will appear : https://github.com/anaseqal/nova-import/issues/13 
If you can use nova action and solve this issue i would appreciate your PR..

Thanks
