### ISSUE TITLE
__(resourceInformation.label) you can, please, remove this from the frontend?

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [anaseqal/nova-import#17]
This is too big a headline for mobile!

**Comment by oleksandr-roskovynskyi** [comment]
```
<svg width="14" height="14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="var(--white)" d="M13 5.41V17a1 1 0 0 1-2 0V5.41l-3.3 3.3a1 1 0 0 1-1.4-1.42l5-5a1 1 0 0 1 1.4 0l5 5a1 1 0 1 1-1.4 1.42L13 5.4zM3 17a1 1 0 0 1 2 0v3h14v-3a1 1 0 0 1 2 0v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-3z"></path></svg>
            <span>{{ __('Import') }} {{ __(resourceInformation.label) }}</span>
```

**Comment by 0xZeus** [comment]
sorry i am not fully sure what you mean.
you mean remove the text and keep icon on mobile?

**Comment by anaseqal** [comment]
sorry i am not fully sure what you mean.
you mean remove the text and keep icon on mobile?

**Comment by oleksandr-roskovynskyi** [comment]
> sorry i am not fully sure what you mean.
> you mean remove the text and keep icon on mobile?

Thanks for the answer! But no, I want you to take the opportunity to turn off or delete:
`{{ __(resourceInformation.label) }}`

**Comment by oleksandr-roskovynskyi** [comment]
Perhaps it would be better if these values are set at the backend rather than rigidly set at the frontend?

**Comment by eoghanobrien** [comment]
I'm having a similar issue, where I want to customize the "label" of the import button but it's currently hardcoded to be 'Import' + resourceInformation.label - There are scenarios where you may want to change the label to something more specific.

For example, if you have a resource for 'Posts', the import button would say 'Import Posts' but what if, you want to only import certain types of posts, let's say 'approved' posts, maybe you would prefer a label like 'Import Approved Posts'. At the moment, if that's the button label you need, you would have to rename your resource from 'Posts' to 'Approved Posts'.

If you were to use the name of the action, I think it would make this a little more robust.

For example, instead of:

```
{{ __('Import') }} {{ __(resourceInformation.label) }}
```

Maybe:

```
{{ __(selectedAction.name) }}
```

Then, as @oleksandr-roskovynskyi  suggests, we could set the label of the import button using PHP:

```php
class ImportPosts extends Action
{
...
    /**
     * Get the displayable name of the action.
     *
     * @return string
     */
    public function name()
    {
        return 'Import Approved Posts';
    }

    /**
     * Get the URI key for the action.
     *
     * @return string
     */
    public function uriKey()
    {
        return 'import-posts';
    }
...
}
```

We also need make sure the `uriKey` method returns the expected value.

Perhaps in order to get around that just add a new `label()` method. Then the developer can specify the button label and avoid worrying about breaking anything else:

```php
class ImportPosts extends Action
{
...
    /**
     * Get the displayable name of the action.
     *
     * @return string
     */
    public function label()
    {
        return 'Import Approved Posts';
    }
...
}
```

Your Action class would then provide the default behavior for `label()`:

```php
class Action implements JsonSerializable
{
    /**
     *  The label of the button.
     *
     * @var string
     */
    public $label;
    ...

    /**
     * The label of the button.
     *
     * @return string
     */
    public function label()
    {
        return $this->label ?: Nova::humanize($this);
    }

    /**
     * Prepare the action for JSON serialization.
     *
     * @return array
     */
    public function jsonSerialize()
    {
        return array_merge([
            'component' => $this->component(),
            'destructive' => $this instanceof DestructiveAction,
            'name' => $this->name(),
            'uriKey' => $this->uriKey(),
            'label' => $this->label(), // Adding this!
            'fields' => collect($this->fields())->each->resolve(new class {
            })->all(),
            'availableForEntireResource' => $this->availableForEntireResource,
            'onlyOnDetail' => $this->onlyOnDetail,
            'onlyOnIndex' => $this->onlyOnIndex,
            'withoutConfirmation' => $this->withoutConfirmation,
            'cancelButtonText' => __($this->cancelButtonText),
            'confirmButtonText' => __($this->confirmButtonText),
            'confirmText' => __($this->confirmText),
        ], $this->meta());
    }
...
}
```

Then in your component, instead of: 

```
{{ __(selectedAction.name) }}
```

You would have:

```
{{ __(selectedAction.label) }}
```

If you think this is a good approach and would accept a pull request, let me know, I'd be happy to create one.

**Comment by anaseqal** [comment]
you can now change the button label in `/resources/lang/vendor/nova/{language}.json` using `Import {uriKey}`, for example:
```"Import users": "Import Users"```

**Comment by borex** [comment]
I have a website set with german as default language and the above mentioned solution didn't work.
For me the problem was solved by adding `"Import Benutzer": "Benutzerimport"`
The action name is set to "Import users" and the uri is "import-users", also in the translation files I have "Users" translated to "Benutzer".
It is interesting because even if I set the translation of the text "Import users", it's still not translating to "Benutzerimport". The action button displays "Import Benutzer". it looks like it's translating partially, leaves the Import as is and is translating the Users part. Looking at the javascript this confirmed it.

Also the "Run Import Action" would be nice to be able to change it.
