### ISSUE TITLE
How did You Get the Import Button Next to the Create User button

### ISSUE THREAD

**Issue by JackiGeduld** [anaseqal/nova-import#6]
Please give me a clear step by step guide on how to you created an import button. 
Thank you

**Comment by aliguzz** [comment]
I followed the step by step guide but still couldn't get the button next to create User or any other nova resource

**Comment by aschechter** [comment]
I too am not able to get the "Import <Resource>" button to show up properly.

I followed the guide and created an Import Items action, and the button successfully showed up.  Then I created another action to import another resource, but the Import button will not show up on the Resource list.

However, if I check the box next to one of the items in the resource list, then the actions menu appears and I can click the action in the dropdown....but this is very counter-intuitive...because my update has nothing to do with the resource I selected.

**Comment by aschechter** [comment]
I discovered one interesting thing in my tests....

Resources (ad by extension Models) that are only one word work.
Orders
Items
....things like this work.

Camel case classes do not appear to work:
OrderItems
SupplierCatalog

I see the following code in:
https://github.com/anaseqal/nova-import/blob/master/resources/js/components/CustomIndexToolbar.vue

`<button
            v-if="hasImportAction"
            data-testid="import-action-confirm"
            dusk="run-import-action-button"
            @click.prevent="openConfirmationModal"
            class="btn btn-default btn-primary"
            :title="__('Run Import Action')"
        >
            <svg width="14" height="14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="var(--white)" d="M13 5.41V17a1 1 0 0 1-2 0V5.41l-3.3 3.3a1 1 0 0 1-1.4-1.42l5-5a1 1 0 0 1 1.4 0l5 5a1 1 0 1 1-1.4 1.42L13 5.4zM3 17a1 1 0 0 1 2 0v3h14v-3a1 1 0 0 1 2 0v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-3z"></path></svg>
            <span>{{ __('Import') }} {{ __(resourceInformation.label) }}</span>
        </button>`

Best I can tell "hasImportAction" is resolving to false on the Resources where the button is not showing up....possibly due to how it it parsing camel-case class names and using that as a comparison to the resource that is being loaded.

        `hasImportAction() {
            // before
            for (let i=0; i<this.actions.length; i++) {
                if(this.actions[i].uriKey == 'import-' + this.resourceName) {
                    return true
                }
            }
            return false
        },`

**Comment by aschechter** [comment]
Son of a gun....read through the closed issues...and I had to pluralize my Action names.  Then the import button showed up.

https://github.com/anaseqal/nova-import/issues/5
